#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/%APP%.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/%APP%.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build -mod vendor -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/%APP%
if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
    GOOS=darwin go build -mod vendor -ldflags "$LINKFLAGS" -o bin/%APP%-darwin
    GOOS=windows go build -mod vendor -ldflags "$LINKFLAGS" -o bin/%APP%-windows
fi
