#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/%APP% .
docker build -t ${REPO}/%APP%:${TAG} .

echo Built ${REPO}/%APP%:${TAG}
